```{r}
source("lib-dendro.R")

library(ggplot2)
library(dplyr)
library(lubridate)
library(glue)

### DEFINE GLOBAL VARS ###
PATH = dirname(rstudioapi::getActiveDocumentContext()$path);
setwd(PATH)

PLACE = 'Miedes'
DATA_DIR = 'processed/Miedes-last'
ENV_DIR = 'processed/Miedes-env-processed'

### IMPORT DENDRO DATA ###

# importing dendro data #
list_files <- list.files(file.path(".",DATA_DIR), pattern="*.csv$", full.names=TRUE)
db<-read.all.processed(list_files)

# Set initial and final date for analysis
ts_start<-"2022-04-01 09:00:00" # 2 days after installation
ts_end<-"2023-09-27 08:00:00" # last timestamp of downloaded data
db <- reset.initial.values(db, ts_start, ts_end)

### CLEAN & PREPARE DATA ###

# INSPECT DATA
str(db)
head(db)
tail(db)
```


```{r}
## PLOT ALL DENDROS ##
plot_multiple_dendro <- function (data, title, y = data$value)  {
  ggplot(data = data, mapping = aes(x=ts, y=y, col=series))+
  geom_line( )+
  # ggtitle(paste0("Dendro data for sensor series: ",db$series[1], " - ", db$sp[1])) +
  labs(x=expression('Date'),
       y=expression( Delta*"D (um)") ) +
  geom_hline(yintercept=0,lty=2,linewidth=0.2)+
  scale_x_datetime(date_breaks = "1 month", date_labels = "%m-%y") +
  ggtitle(title) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 30, hjust=1))
}
```

```{r}
plot_multiple_dendro(db, "Plot by dendrometer")
ggsave(glue('output/all-dendrometers-{PLACE}.png'), width = 15, height = 10)
```

# Normalization 0-1 to better compare dendros

```{r}
normalized.db <- db %>%
  select (series, ts, value) %>%
  group_by(series) %>%
  mutate( normalized_value = normalize.0_1(value), .keep = 'all' )
```


```{r}
plot_multiple_dendro(normalized.db, "Dendros data normalized to [0-1]", y = normalized.db$normalized_value)
ggsave(glue('output/normalized-all-dendrometers-{PLACE}.png'), width = 15, height = 10)
```


# Mean + strip region of SE
```{r}
dbagg = db %>% group_by(ts) %>% dplyr::summarise(mean = mean(value, na.rm = T), sd = sd(value, na.rm = T) )

#library(Rmisc) # for summarySE()
#dbagg <- summarySE(db, measurevar = "value", groupvars = c("ts"), na.rm = TRUE)
head(dbagg)
tail(dbagg)
```

```{r}
plot_cat_full_year<-
  ggplot(data = dbagg,  aes(x=ts, y=mean)) +
  ggtitle("Mean of data for Miedes dendrometers with ± standard deviation strips") +
  geom_ribbon(aes(ymin=mean-sd, ymax=mean+sd), fill='lightgreen', alpha=0.3, show.legend	= FALSE, linetype = 0) +
  geom_line( aes (linetype = ""), col='darkgreen', show.legend	= F) +
  labs(x=expression(''),
       y=expression(Delta*" D (um)"))+
  theme_bw() +
  geom_hline(yintercept=0,lty=2,linewidth=0.2)+
  #facet_grid(class~.,scales = "free_y")+
  scale_x_datetime(date_breaks = "1 month", date_labels="%b %Y") +
  theme(axis.text.x = element_text(angle = 30, hjust=1))
plot_cat_full_year
ggsave(glue('output/mean-{PLACE}.png'), width = 15, height = 10)
```


# By species

```{r}
TreeList<-read.table("TreeList.txt",header=T)

Qi = TreeList %>% filter(class == "Quercus") %>% pull(series)
P_D = TreeList %>% filter(class == "D") %>% pull(series)
P_ND = TreeList %>% filter(class == "ND") %>% pull(series)

db.Qi = db %>% filter (series %in% Qi)
db.D = db %>% filter (series %in% P_D)
db.ND = db %>% filter (series %in% P_ND)
```

One plot of dendros by class:
```{r}
plot_multiple_dendro(db.Qi, "Quercus Ilex - Miedes", y = db.Qi$value)
ggsave(glue('output/Qi-{PLACE}.png'), width = 15, height = 10)
```

```{r}
plot_multiple_dendro(db.ND, "Non-Declining - Miedes", y = db.ND$value)
ggsave(glue('output/ND-{PLACE}.png'), width = 15, height = 10)
```

```{r}
plot_multiple_dendro(db.D, "Declining - Miedes", y = db.D$value)
ggsave(glue('output/D-{PLACE}.png'), width = 15, height = 10)
```


```{r}
db.Qi.agg <- db.Qi %>% group_by(ts) %>% dplyr::summarise(mean = mean(value, na.rm = T), sd = sd(value, na.rm = T) )
head(db.Qi.agg)
tail(db.Qi.agg)
```


```{r}
#library(mdthemes)
plot_mean_sd <- function (data, species, output_fn = FALSE) {
  plot <-
    ggplot(data = data,  aes(x=ts, y=mean)) +
    ggtitle(paste0("Mean of data for ", species, " with ± standard deviation strips")) +
    geom_ribbon(aes(ymin=mean-sd, ymax=mean+sd), fill='lightgreen', alpha=0.3, show.legend	= FALSE, linetype = 0) +
    geom_line( aes (linetype = species), col='darkgreen', show.legend	= T) +
    labs(x=expression(''),
         y=expression(Delta*" D (um)")) +
    theme_bw() +
    #md_theme_bw()+
    geom_hline(yintercept=0,lty=2,linewidth=0.2) +
    #facet_grid(class~.,scales = "free_y")+
    scale_x_datetime(date_breaks = "1 month", date_labels="%b %Y") +
    theme(axis.text.x = element_text(angle = 30, hjust=1))
        
  plot(plot)
  if (output_fn != F){
    ggsave(output_fn, width = 15, height = 10)  
  }
}
```


```{r}
plot_mean_sd(db.Qi.agg, "Quercus Ilex", output_fn = glue("output/mean-Qi-{PLACE}.png"))
```


```{r}
db.D.agg <- db.D %>% group_by(ts) %>% dplyr::summarise(mean = mean(value, na.rm = T), sd = sd(value, na.rm = T) )
head(db.D.agg)
tail(db.D.agg)
```


```{r}
plot_mean_sd(db.D.agg, "Declining Pinus", output_fn = glue("output/mean-declining-{PLACE}.png") )
```

```{r}
db.ND.agg <- db.ND %>% group_by(ts) %>% dplyr::summarise(mean = mean(value, na.rm = T), sd = sd(value, na.rm = T) )
head(db.ND.agg)
tail(db.ND.agg)
```


```{r}
plot_mean_sd(db.ND.agg, "Not Declining Pinus", output_fn = glue("output/mean-ND-{PLACE}.png") )
```

Join all aggregated df in one
```{r}
db.Qi.agg$class = factor("Quercus Ilex")
db.D.agg$class = factor("Declining Pinus")
db.ND.agg$class = factor("Non-Declining Pinus")
db.by.class.agg = rbind.data.frame(db.Qi.agg, db.D.agg, db.ND.agg)
str(db.by.class.agg)
```

Plot mean by class in one plot
```{r}
plot_multiple_dendro_by_class <-
  ggplot(data = db.by.class.agg, mapping = aes(x=ts, y=mean, col = class))+
  geom_line( ) +
  # ggtitle(paste0("Dendro data for sensor series: ",db$series[1], " - ", db$sp[1])) +
  labs(x=expression('Date'),
       y=expression( Delta*"D (um)") ) +
  geom_hline(yintercept=0,lty=2,linewidth=0.2)+
  scale_x_datetime(date_breaks = "1 month", date_labels = "%m-%y") +
  ggtitle("Means by class") +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 30, hjust=1))
plot_multiple_dendro_by_class
ggsave(glue('output/mean-byclass-{PLACE}.png'), width = 15, height = 10)
```


Plot all dendros by class in one graph (WIP)

```{r}
db.by.class = db %>% select(series, ts, value) %>% mutate(class =  case_when(
                                      series %in% Qi ~ "Quercus",
                                      series %in% P_D ~ "Declining",
                                      series %in% P_ND ~ "Non-Declining"
                                      )
)
```

```{r}
library(ggnewscale)

# Define color scales for each class
green_colors <- c("lightgreen", "green", "darkgreen", "darkolivegreen", "olivedrab", "springgreen")
blue_colors <- c("blue", "cyan", "aquamarine", "cadetblue", "dodgerblue", "darkblue")
orange_colors <- c("orange", "orangered", "tomato", "darkorange", "coral", "tan")

ggplot() +
   ggtitle("Dendrometers painted by color scale according to its class") +
  geom_line(data = db.D, aes(x = ts, y = value, col = series)) +
  scale_color_manual(values = orange_colors, name = "Declining trees") +
  new_scale_color() +
  geom_line(data = db.ND, aes(x = ts, y = value, col = series), ) +
  scale_color_manual(values = blue_colors, name = "Non-Declining trees") +
  new_scale_color() +
  geom_line(data = db.Qi, aes(x = ts, y = value, col = series)) +
  scale_color_manual(values = green_colors, name = "Quercus Ilex") +
  geom_hline(yintercept=0,lty=2,linewidth=0.2) +
  labs(x=expression(''),
       y=expression(Delta*" D (um)"))+
  theme_bw() +
  scale_x_datetime(date_breaks = "1 month", date_labels="%b %Y") +
  theme(axis.text.x = element_text(angle = 30, hjust=1))

ggsave(glue('output/all-dendrometers-by-class-{PLACE}.png'), width = 15, height = 10)
```

# Environmental data from TMS sensors

```{r}
# importing processed environmental data #
db.env<-read.env.proc(file.path(PATH,ENV_DIR,'proc-env.csv'))
str(db.env)
```

```{r}
plot_multiple_env <- function (data, title, y = data$value, unit)  {
  ggplot(data = data, mapping = aes(x=ts, y=y, col=series))+
  geom_line( )+
  # ggtitle(paste0("Dendro data for sensor series: ",db$series[1], " - ", db$sp[1])) +
  labs(x=expression('Date'),
       y=unit ) +
  geom_hline(yintercept=0,lty=2,linewidth=0.2)+
  scale_x_datetime(date_breaks = "1 month", date_labels = "%m-%y") +
  ggtitle(title) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 30, hjust=1))
}
```

```{r}
plot_multiple_env(db.env, "Temperature per TMS sensor", y = db.env$temp, "Temperature (ºC)")
```


```{r}
plot_multiple_env (db.env, "Volumetric Water Content per TMS sensor", y = db.env$vwc, "VWC (%)")
ggsave(glue('output/vwc-{PLACE}.png'), width = 15, height = 10)
```

Now calculate the mean for vwc and temp:
```{r}
db.env.agg = db.env %>% group_by(ts) %>% dplyr::summarise(temp = mean(temp, na.rm = T), vwc = mean(vwc, na.rm = T))
db.env.agg
```

And we plot it:

```{r}
plot_temp_and_humidity <-
  ggplot(data = db.env.agg, aes(x=ts, y=temp)) +
    ggtitle("Temperature and humidity for Miedes (2022-2023)") +
    geom_line(aes(colour = temp)) +
    theme_bw() +
    scale_colour_gradient(low = "light blue", high = "red") +
    scale_x_datetime(date_breaks = "1 month", date_labels="%b %Y") +
    theme(axis.text.x = element_text(angle = 30, hjust=1)) +
    scale_y_continuous("Temperature (ºC)", breaks=seq(0,50,10), sec.axis = dup_axis(name = "Volumetric Water Content (%)" ))+
    geom_line(aes(x = ts, y = vwc * 100,  linetype = "Volumetric Water Content (%)"), col="blue", show.legend	= TRUE) +
    scale_linetype_manual(NULL, values = 1) +
    labs(x=expression(''), colour = "Temperature (ºC)")
plot_temp_and_humidity
ggsave(glue('output/VWCytempAgg-{PLACE}.png'), width = 15, height = 10)
```
