---
title: "R Notebook"
output: html_notebook
---

```{r}
source('lib-dendro.R')
library(ggplot2)
library(tidyverse)
library(glue)
library(patchwork)
```

ggplot custom theme
```{r}
theme_set( theme_bw() +
          theme(
            axis.text=element_text(size=12),
            legend.text=element_text(size=10),
            axis.title=element_text(size=14),
            plot.title = element_text(hjust = 0.5, face = "bold")
          ))
```


```{r}
TreeList <- read.table("TreeList.txt", header=T)

PLACE = 'Miedes'
DATA_DIR = glue('processed/{PLACE}-processed')
ENV_DIR = glue('processed/{PLACE}-env-processed')


SELECTED_TMS <- case_when(  # select one TMS sensor for this site which has all its data valid
  PLACE == 'Miedes' ~ "94231940",
  PLACE == 'Corbalan' ~ "94231943",
  PLACE == 'Penaflor' ~ "94231934",
  .default = NA
)
```

Load dataset:
```{r}
list_files <- list.files(file.path(".",DATA_DIR), pattern="*.csv$", full.names=TRUE)
db<-read.all.processed(list_files)
head(db)

db.env <- read.env.proc(file.path(".",ENV_DIR,'proc-env.csv'))
db.env <- db.env[db.env$series == SELECTED_TMS,]
head(db.env)
```
Define classes which each series belong to:
```{r}
Qi = TreeList %>% filter(class == "Quercus", series %in% unique(db$series)) %>% pull(series)
P_D = TreeList %>% filter(class == "D", series %in% unique(db$series)) %>% pull(series)
P_ND = TreeList %>% filter(class == "ND", series %in% unique(db$series)) %>% pull(series)
```

Prepare db
```{r}
db = db %>% mutate(
                  date = date(db$ts),
                  class = case_when(
                    series %in% Qi ~ factor("Quercus"),
                    series %in% P_D ~ factor("D"),
                    series %in% P_ND ~ factor("ND"),
                    .default = NA
                    )
                  ) %>%
            filter(!is.na(class))
db
```

# TWD
```{r}
db.twd <- db %>% summarise( mean_twd = mean(twd, na.rm = T), twd_se = sd(twd / sqrt(n()), na.rm = T), .by = c(date, class), n = as.integer(n() / 96)) %>% mutate(doy = yday(date))
db.twd2022 <- db.twd %>% filter(year(date) == 2022)
db.twd2023 <- db.twd %>% filter(year(date) == 2023)
db.twd
```

```{r}
Q_n <-  db.twd %>% filter(class == "Quercus") %>% select(n) %>% max()
D_n <-  db.twd %>% filter(class == "D") %>% select(n) %>% max()
ND_n <- db.twd %>% filter(class == "ND") %>% select(n) %>% max()
```

```{r}
labels = c("Quercus", "Declining Pines", "Non-Declining Pines")
c_labels = c(glue("{labels[1]} ({Q_n})"), glue("{labels[2]} ({D_n})"), glue("{labels[3]} ({ND_n})"))
```

Boxplot:
```{r}
plot.twd2022 <- db.twd2022 %>%
  ggplot () +
  geom_boxplot(aes (x = class, y = mean_twd, color = class)) +
   scale_color_manual(labels = c_labels, values=c(Quercus = "green", D = "darkred", ND = "darkorange")) +
  labs(title = "2022", x = "Class", y = "Tree Water Deficit") +
  scale_x_discrete(labels=c("Q" = labels[1], "D" = labels[2],
                              "ND" = labels[3]))

plot.twd2023 <- db.twd2023 %>%
  ggplot () +
  geom_boxplot(aes (x = class, y = mean_twd, color = class)) +
   scale_color_manual(labels = c_labels, values=c(Quercus = "green", D = "darkred", ND = "darkorange")) +
  labs(title = "2023", x = "Class", y = "Tree Water Deficit") +
  scale_x_discrete(labels=c("Q" = labels[1], "D" = labels[2],
                              "ND" = labels[3]))

combined <- (plot.twd2022 | plot.twd2023) + plot_layout(guides = "collect", axis_titles = "collect") + plot_annotation(title = glue('Boxplot of TWD dispersion - {PLACE}')) & theme(legend.position = "bottom")
combined
```
```{r}
ggsave(glue('output/boxplot-TWD-byClass-{PLACE}.png'), combined, width = 14, height = 6)
```

Continuous TWD evolution along with VWC:

```{r}
vwc <- db.env %>% mutate(date = date(db.env$ts)) %>% summarise(max = max(vwc), .by = date)
vwc
```


```{r}
plot.twd2023 <- db.twd %>%
  ggplot () +
  geom_line(aes (x = date, y = mean_twd, color = class), show.legend = T) +
  geom_line(aes (x = date, y = (mean_twd + twd_se), color = class), alpha = 0.5, linetype = "dashed", show.legend = F) +
  geom_line(aes (x = date, y = (mean_twd - twd_se), color = class), alpha = 0.5, linetype = "dashed", show.legend = F) +
  scale_color_manual(labels = c_labels, values=c(Quercus = "green", D = "darkred", ND = "darkorange")) +
  labs(title = "2023", x = "Date", y = "Tree Water Deficit") +
  scale_x_date(limits = as.Date(c("2023-01-01", "2023-12-31")), breaks = seq(as.Date("2023-01-01"), as.Date("2023-12-31"), by = "1 month"), date_labels = "%b-%y") +
  scale_y_continuous(sec.axis = sec_axis(trans = ~ . /10, name = "Volumetric Water Content (%)")) +
   geom_line(data = vwc, aes(x = date, y = max*1000, linetype = "Volumetric Water Content (%)"), col = "blue", alpha = 0.8, show.legend	= c(colour = FALSE, linetype = T)) +
  scale_linetype_manual(NULL, values = 4)

plot.twd2022 <- db.twd %>%
  ggplot () +
  geom_line(aes (x = date, y = mean_twd, color = class), show.legend = T) +
  geom_line(aes (x = date, y = (mean_twd + twd_se), color = class), alpha = 0.5, linetype = "dashed", show.legend = F) +
  geom_line(aes (x = date, y = (mean_twd - twd_se), color = class), alpha = 0.5, linetype = "dashed", show.legend = F) +
  scale_color_manual(labels = c_labels, values=c(Quercus = "green", D = "darkred", ND = "darkorange")) +
  labs(title = "2022", x = "Date", y = "Tree Water Deficit") +
  scale_x_date(limits = as.Date(c("2022-01-01", "2022-12-31")), breaks = seq(as.Date("2022-01-01"), as.Date("2022-12-31"), by = "1 month"), date_labels = "%b-%y") +
  scale_y_continuous(sec.axis = sec_axis(trans = ~ . /10, name = "Volumetric Water Content (%)")) +
   geom_line(data = vwc, aes(x = date, y = max*1000, linetype = "Volumetric Water Content (%)"), col = "blue", alpha = 0.8, show.legend	= c(colour = FALSE, linetype = T)) +
  scale_linetype_manual(NULL, values = 4)

combined <- plot.twd2022 / plot.twd2023 + 
  plot_layout(guides = "collect", axis_titles = "collect") + 
  plot_annotation(title = glue('TWD evolution by classes along with Soil Moisture - {PLACE}')) &
  theme(legend.position = "bottom")
combined
```
```{r}
ggsave(glue('output/evolution-TWD-byClass-{PLACE}.png'), combined, width = 14, height = 6)
```

Same but now along with temp min and temp max:

```{r}
temp <- db.env %>% mutate(date = date(db.env$ts)) %>% summarise(tmax = max(surface.temp), tmin = min(surface.temp), .by = date)
temp
```

```{r}
plot.twd2023 <- db.twd %>%
  ggplot () +
  geom_line(aes (x = date, y = mean_twd, color = class), show.legend = T) +
  geom_line(aes (x = date, y = (mean_twd + twd_se), color = class), alpha = 0.5, linetype = "dashed", show.legend = F) +
  geom_line(aes (x = date, y = (mean_twd - twd_se), color = class), alpha = 0.5, linetype = "dashed", show.legend = F) +
  scale_color_manual(labels = c_labels, values=c(Quercus = "green", D = "darkred", ND = "darkorange")) +
  labs(title = "2023", x = "Date", y = "Tree Water Deficit", alpha = "Climate") +
  scale_x_date(limits = as.Date(c("2023-01-01", "2023-12-31")), breaks = seq(as.Date("2023-01-01"), as.Date("2023-12-31"), by = "1 month"), date_labels = "%b-%y") +
  scale_y_continuous(sec.axis = sec_axis(trans = ~ . /10, name = "Temperature (ºC)")) +
  geom_linerange(data = temp, aes(x = date, ymin = tmin*10, ymax = tmax*10, alpha = "temp"), col = "firebrick2") +
  scale_alpha_manual(labels = c("Range from minimum to maximum temperature (ºC)"), values = c(temp = 0.6)) # to set legend text

plot.twd2022 <- db.twd %>%
  ggplot () +
  geom_line(aes (x = date, y = mean_twd, color = class), show.legend = T) +
  geom_line(aes (x = date, y = (mean_twd + twd_se), color = class), alpha = 0.5, linetype = "dashed", show.legend = F) +
  geom_line(aes (x = date, y = (mean_twd - twd_se), color = class), alpha = 0.5, linetype = "dashed", show.legend = F) +
  scale_color_manual(labels = c_labels, values=c(Quercus = "green", D = "darkred", ND = "darkorange")) +
  labs(title = "2022", x = "Date", y = "Tree Water Deficit", alpha = "Climate") +
  scale_x_date(limits = as.Date(c("2022-01-01", "2022-12-31")), breaks = seq(as.Date("2022-01-01"), as.Date("2022-12-31"), by = "1 month"), date_labels = "%b-%y") +
  scale_y_continuous(sec.axis = sec_axis(trans = ~ . /10, name = "Temperature (ºC)")) +
  geom_linerange(data = temp, aes(x = date, ymin = tmin*10, ymax = tmax*10, alpha = "temp"), col = "firebrick2") +
  scale_alpha_manual(labels = c("Range from minimum to maximum temperature (ºC)"), values = c(temp = 0.6)) # to set legend text

combined <- plot.twd2022 / plot.twd2023 + 
  plot_layout(guides = "collect", axis_titles = "collect") + 
  plot_annotation(title = glue('TWD evolution by classes along with Daily Temperature - {PLACE}')) &
  theme(legend.position = "bottom")
combined
```

```{r}
ggsave(glue('output/evolution-Temp-byClass-{PLACE}.png'), combined, width = 14, height = 6)
```


# GRO
```{r}
db.gro <- db %>% summarise( gro = mean(gro_yr, na.rm = T), gro_se = sd(gro_yr / sqrt(n()), na.rm = T), .by = c(date, class)) %>% mutate(doy = yday(date))
db.gro2022 <- db.gro %>% filter(year(date) == 2022)
db.gro2023 <- db.gro %>% filter(year(date) == 2023)
db.gro
```

```{r}
plotgro2022 <- db.gro2022 %>% 
  ggplot() +
  ggtitle('2022') +
  geom_line(aes (x = doy, y = gro, color = class)) +
  geom_line(aes (x = doy, y = (gro + gro_se), color = class), alpha = 0.5, linetype = "dashed") +
  geom_line(aes (x = doy, y = (gro - gro_se), color = class), alpha = 0.5, linetype = "dashed") +
  labs(x = "Day of the year", y = expression(paste("Acumulated growth (",mu, "m)")) ) +
  scale_color_manual(labels = c_labels, values=c(Quercus = "green", D = "darkred", ND = "darkorange")) +
  scale_x_continuous(breaks = seq(0, 360, by = 30), limits = c(0, 366))

plotgro2023 <- db.gro2023 %>% ggplot () +
  ggtitle('2023') +
  geom_line(aes (x = doy, y = gro, color = class)) +
  geom_line(aes (x = doy, y = (gro + gro_se), color = class), alpha = 0.5, linetype = "dashed") +
  geom_line(aes (x = doy, y = (gro - gro_se), color = class), alpha = 0.5, linetype = "dashed") +
  labs(x = "Day of the year", y = expression(paste("Acumulated growth (",mu, "m)")) ) +
  scale_color_manual(labels = c_labels, values=c(Quercus = "green", D = "darkred", ND = "darkorange")) +
  scale_x_continuous(breaks = seq(0, 360, by = 30), limits = c(0, 366))

combined <- plotgro2022 / plotgro2023 + plot_layout(guides = "collect", axis_titles = "collect") + plot_annotation(title = glue('Acumulated Growth - {PLACE}')) & theme(legend.position = "bottom")
combined
```

```{r}
ggsave(glue('output/GRO-byClass-{PLACE}.png'), combined, width = 14, height = 6)
```

